# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aca5ce8fb48673108e57ea5a6a1d329a66eacbf8dbbf74c03063252d64d606a3e6bb5a6a9848e480821d33c252280aaca5a2a265fcb1cec7d54b9463abcf13a

test:
  secret_key_base: 1c97d2e66c774e68210b595d5fc8a899fd58548821fda956a1ff1da27ee92fd4c59bc86773462516acd2f303af29c7a90cb2dd76c5f4628fca3a3e87f39cf951

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
